server:
  port: 8083

spring:
  application:
    name: vacancy-service

  logging:
    level:
      org.springframework.cloud.gateway: INFO
      com.vlz: DEBUG

  clients:
    user-service:
      name: user-service
      url: http://localhost:8082

  retry:
    max-attempts: 3
    delay: 1000

  vacancy-create:
    role: EMPLOYER

  datasource:
    url: jdbc:postgresql://localhost:5435/vacancydb
    username: vacancyuser
    password: vacancypass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

kafka:
  bootstrap-servers: localhost:9092
